### ISSUE TITLE
Global refactoring

### ISSUE THREAD

**Issue by foliea** [grounds/grounds-exec#33]
grounds-exec currently has a technical debt.

## Tests
- [x] Reorganize file tree: (`test/lib`, `test/feature`). **ok**
- [x] Extract runner test examples to integration tests. **ok**
- [x] Unit test properly the runner. **ok (but still has a dependency on docker)**
- [x] Figure out a way to test ruby output sync.
- [x] Add cli tests. **ok**

## Code
- [x] Connection: spam prevention is ugly as hell.
- [x] Connection on run: should verify and format Runner params (with validator).
- [x] Logger is not DRY. **ok**
- [x] Runner should be able to run many times.
- [x] Each module should have its own errors like runner.
- [x] Runner should emit real errors event.
- [x] Runner should have a state machine.
- [x] Runner should not keep language and language. (pass it to run method).
- [x] Improve error handling. **ok**
- [x] Extract CLI as a module. **ok**
- [x] Add tests for server listen (both in CLI and Server).

## Build
- [x] Use latest `node` release. **ok**
- [x] Add `all` and `re` rules to make. **ok**
- [x] Remove prefixes from exec image directories (images should still be named with this prefix). **ok**

**Comment by folieadrien** [comment]
Related to #53
